### ISSUE TITLE
Usage of WeakReference<Context>

### ISSUE THREAD

**Issue by giovannivelludo** [Cogno-IDU/smslibrary#22]
Why are we using a WeakReference to a Context in `SMSHandler`? I thought the memory leak problem presented itself only when field `context` was declared `static` (because this prevented garbage collection of that `Context`), not when a field contains a reference to a Context in general.

**Comment by CremaLuca** [comment]
The `context` becomes kind of a static variable when you use a singleton: the variable `instance` cannot be garbage collected because it has a valid reference to a `context`. Android Studio warns you about this kind of memory leak too.

**Comment by giovannivelludo** [comment]
I'm getting a warning on the `static` declaration of `instance`, but I'll explain why I don't think it's a problem.

From my understanding of how garbage collection works, an object can be garbage collected when there are no more references to it. This is why declaring a `Context` variable as `static` prevents it from getting garbage collected, because it's not tied to an instance of an object (which can be unreferenced and therefore garbage collected), but it's instead tied to a class, and a class cannot be unreferenced.

In the case of class `SMSHandler`, we have a static reference to the current `instance` of `SMSHandler`, which means that `instance` is never garbage collected. Since our `instance` needs `context` to contain a `Context` in order to function properly, we shouldn't let that `Context` be garbage collected either. In fact, if that field happens to get garbage collected, our `SMSHandler` will throw a `NullPointerException` when accessing it, for example when setting up listeners. Now that I think about it, this might also happen if the `Activity` we passed as `Context` is destroyed, so in the branch I'm currently working I changed the assignment of `context` in `setup()` to `this.context = context.getApplicationContext();`.

**Comment by MatteoCarnelos** [comment]
An eligible solution would be to ask for the context inside the methods that needs it. In this way the context will be dereferenced and will became garbage-collectable once the method is terminated.

By doing this we have also some pros:
1. **The class is more "plug-and-play".** This because the user doesn't have to call the setup function before doing anything (most of the times the user doesn't even now that he has to do that because not all users read the specifics).
2. **The context is requested only on those functions that really needs it.** We all know that getting the context outside the activity classes it's often tricky. For example the `sendMessage(...)` method without sent/delivered listeners does not request any context, but the user should call the `setup` function, passing the context, anyway (specifics suggests it), even if it is only using that particular method.
3. **The sent and delivered receivers can be tied to different contexts.** It's a rare case and I don't have any good example to show, but it could happen.
4. **@Cogno-IDU will be helped in his pull request #15 .**

The only con I see with this change is the fact that some methods will have one more argument.

**Comment by Cogno-IDU** [comment]
Due to recent changes with pull request I have to update the class in my pull request, I could update and fix this issue in there too. But I would close the pull request and open a new one with everything.

**Comment by giovannivelludo** [comment]
@MatteoCarnelos
> An eligible solution would be to ask for the context inside the methods that needs it. In this way the context will be dereferenced and will became garbage-collectable once the method is terminated.

This is not an issue when holding a static reference to the application Context(I did this in the branch I'm working on by using `context.getApplicationContext()` in the `SMSManager` constructor), because it's garbage collected only when the application is destroyed, so we're not preventing any garbage collection.
I agree that requiring a Context in methods that use it would be a more elegant solution, however it complicates life for the user, because they'll have to choose which Context to pass depending on the method. We could solve this by getting the application Context every time a Context is passed, but then we might as well ask for the Context only once and hold a reference to it.
If there are any downsides to always using an application Context I'd go with your solution.

**Comment by Cogno-IDU** [comment]
wasn't a static reference to a context a memory leak?
Anyway, I don't see any difference from asking it from the user and using getApplicationContext().

**Comment by giovannivelludo** [comment]
@Cogno-IDU A Context such as an Activity might need to be garbage collected when the Activity is destroyed, and a static pointer to it would prevent this. The application Context however won't be garbage collected as long as our app is running. The only class that is activated when the app is closed is SMSReceivedBroadcastReceiver, and that uses a Context passed by Android to its onReceive() method.

**Comment by RicDeZen** [comment]
I'll just add some stuff I know, the proposed solution doesn't need to change based on them.
*In our case* Giovanni is right, the Android system can kill a process forcefully, ignoring Context references to some extent.
Keeping the reference would be an issue if we registered some other component to the Context (even more so if it's the application Context), like a BroadcastReceiver or a Service. The former is the case for group 1's library and it's the reason why we have a onContextDestroyed() method to make sure the BroadcastReceiver is unregistered and the reference removed.
If that's not done the Debugger will log an error, altough the application cannot crash because it's literally not there anymore.
Even if it's not necessary I live by "better safe than sorry", so I'd have left the WeakReference there, considering it doesn't impact our library's functionality in the slightest if such a WeakReference is the app Context, but I can't force you all to roll back since I came so late to the party.
In general a static reference to a Context is a bad practice. The fact our specific scenario doesn't let us see the consequences of this misbehaviour doesn't imply the misbehaviour isn't there.

**Comment by giovannivelludo** [comment]
Ok, if using WeakReference will prevent that error then I would keep it

**Comment by RicDeZen** [comment]
We would still need an onContextDestroyed method to prevent the error, kinda like the opposite of setup, WeakReference is just a fail-safe and personal preference really

**Comment by MatteoCarnelos** [comment]
It seems that with any of these solutions we don't have any problem of memory leakage.
At the end the solution I posted was approved and merged, I think that this issue con be considered closed.
