### ISSUE TITLE
Continuous Integration Error

### ISSUE THREAD

**Issue by Cogno-IDU** [Cogno-IDU/smslibrary#38]
Today (28/12/2019) Our Android CI Action Returned an error.

The error was caused at commit `08f4b54`, which comes from #36 

An interesting part of the error is some failed unit-tests:

```
22 tests completed, 7 failed
> Task :smslibrary:testDebugUnitTest FAILED

com.eis.smslibrary.SMSPeerTest > validPeers_areCreated FAILED
    com.eis.smslibrary.exceptions.InvalidTelephoneNumberException at SMSPeerTest.java:70

com.eis.smslibrary.SMSPeerTest > shortPeer_isNotCreated FAILED
    java.lang.AssertionError at SMSPeerTest.java:92

com.eis.smslibrary.SMSPeerTest > validAddressed_areCompared FAILED
    com.eis.smslibrary.exceptions.InvalidTelephoneNumberException at SMSPeerTest.java:114

com.eis.smslibrary.SMSPeerTest > emptyPeer_isNotCreated FAILED
    java.lang.AssertionError at SMSPeerTest.java:84

com.eis.smslibrary.SMSPeerTest > validPeers_areEqual FAILED
    com.eis.smslibrary.exceptions.InvalidTelephoneNumberException at SMSPeerTest.java:121

com.eis.smslibrary.SMSPeerTest > validPeersHashes_areEqual FAILED
    com.eis.smslibrary.exceptions.InvalidTelephoneNumberException at SMSPeerTest.java:130

com.eis.smslibrary.SMSPeerTest > longPeer_isNotCreated FAILED
    java.lang.AssertionError at SMSPeerTest.java:100
```

I checked why those tests were failing, but I was **NOT** able to recreate the issue, on my end all the tests were running fine.

You can find more information [here](https://github.com/Cogno-IDU/smslibrary/runs/365945800)

**Comment by MatteoCarnelos** [comment]
I think that I've found the problem.
In the tests I verify some Italian telephone numbers without the prefix. In our Italian laptops the prefix automatically added is "+39" but in the GitHub JVM is probably the American one (+1). This invalidates the number and makes the tests fail.
The solution for this problem is to set the default added prefix to the Italian one in tests with the method `SMSPeer.setDefaultRegion(...)`. 
I'll fix it ASAP and re-open the pull request.
